### ISSUE TITLE
Style Editor Error

### ISSUE THREAD

**Issue by afabiani** [GeoNode/geonode-mapstore-client#3] opened 2019-07-24 13:11 UTC
Geonode 2.10
Mapstore2 Client 1.3.1

![style_error](https://user-images.githubusercontent.com/15963902/60396373-7a7bf880-9b73-11e9-8979-faa1982357f2.png)

Meanwhile in Chrome developer console, it says these:

> 404 Not found http://192.168.11.246:9090/gs/geonode:fe_2007_02_county/style-check?access_token=0YJ9ywamKOL5u9r5kz8WLukh9AJ9xy ms2-geonode-api.js:15 

> 404 Not found http://192.168.11.246:9090/gs/geonode/fe_2007_02_county/ows?service=WMS&version=1.3.0&request=GetCapabilities&access_token=0YJ9ywamKOL5u9r5kz8WLukh9AJ9xy ms2-geonode-api.js:15

**Comment by gannebamm** [comment] 2019-10-15 10:24
I will close this since I am unable to reproduce it on master.demo.geonode.org

**Closed by gannebamm** 2019-10-15 10:24 UTC
Labels: bug

**Comment by diegodoy** [comment] 2021-06-21 15:26
I have the same issue
