### ISSUE TITLE
Showing metadata per layer in map

### ISSUE THREAD

**Issue by gannebamm** [GeoNode/geonode-mapstore-client#1616] opened 2023-11-14 11:52 UTC
**Problem:** When I, as a viewer, look at a map with multiple data layers, I do not get detailed information about the layers used in the map without leaving it. So far, I can look at the map, but this jumps to the respective data set and the map is exited.

![grafik](https://github.com/GeoNode/geonode-mapstore-client/assets/6172324/5aececa6-c299-49cf-971d-51d28d50d00e)

**Objective:** As a viewer, I would like to be able to display the detail panel of the layer on the right-hand side via an additional layer on the right side. For this, I do not leave the map view. A mockup is shown in the following figure.

![grafik](https://github.com/GeoNode/geonode-mapstore-client/assets/6172324/d7970f35-1532-448d-9066-1697aad2575f)

**Comment by gannebamm** [comment] 2023-11-14 11:54
Thünen has worked on that idea and provides a PR solution here: https://github.com/Thuenen-GeoNode-Development/geonode-mapstore-client/pull/22

If this is interesting for a general audience we will upstream the feature

**Comment by gannebamm** [comment] 2023-12-20 13:02
@allyoucanmap @giohappy Do you think this is interesting for a wider audience and shall we prepare a proper PR for this?

**Comment by giohappy** [comment] 2023-12-21 09:24
@gannebamm looks interesting and useful indeed!
Yes please open a PR. However, I cannot guarantee we will be able to have a look soon, since we're closing for Christmas.

**Comment by giohappy** [comment] 2024-03-14 17:20
@gannebamm any chance to take a look at the code (PR) for this feature?

**Comment by ridoo** [comment] 2024-03-15 15:08
@giohappy we have regression with this since `v4.2.2`: The linked resources have to be mapped now (as it is [done in the DetailViewer](https://github.com/Thuenen-GeoNode-Development/geonode-mapstore-client/blob/ce3b453bba9fbe9089424fd032c31ca88a7ad606/geonode_mapstore_client/client/js/epics/detailviewer.js#L29-L32)). The point here is, that the linked resources endpoint is only available on `/resources` but not `/datasets` which includes the `attribute_set` rendered in the Attributes tab. @ahmdthr is figuring out how to deal with this .. for example, if making a second request to `/datasets` would be needed (which is not very nice solution TBH).

**Comment by gannebamm** [comment] 2024-03-19 08:37
@giohappy I know it is not a PR and not tracking master, but the latest code @ahmdthr has done is listed here: https://github.com/Thuenen-GeoNode-Development/geonode-mapstore-client/pull/22/files

As @ridoo said there are still some issues. Shall we create a draft PR?

**Comment by ridoo** [comment] 2024-03-19 09:40
@gannebamm I am doing a re-test as @ahmdthr says, it works on his machine. However, AFAIK the linked_resources endpoint is only available for resources, not datasets. Maybe I am overlooking something ...

**Comment by ridoo** [comment] 2024-03-19 18:15
Everything is merged and can be tested

**Comment by giohappy** [comment] 2024-03-22 17:24
@ridoo @gannebamm I invite you to keep this on hold for a few hours. We're about to merge a https://github.com/GeoNode/geonode/pull/12080 that will make `linked_resources` available inside all the resources endpoints if the `?include[]=linked_resources` GET parameter is used.
This was done to avoid having to do too many additional requests (that will particularly affect the new development for the mapviewers)

**Comment by gannebamm** [comment] 2024-07-25 13:12
We will start working on this again soon.

**Closed** 2024-12-04 11:56 UTC
Labels: enhancement, feature
