### ISSUE TITLE
Error in GetFeatureInfo rendering when more than one layer in map

### ISSUE THREAD

**Issue by marthamareal** [GeoNode/geonode-mapstore-client#567] opened 2021-11-04 12:32 UTC
There is a difference in the rendering of a getfeatureinfo in the maps when there are more than 1 layer:

![image](https://user-images.githubusercontent.com/717359/138449612-1e41c1f5-9faf-4798-8970-34c3e73fcd39.png)
![image](https://user-images.githubusercontent.com/717359/138449633-debce988-1eea-4e19-b813-43fcc00c2633.png)

In the latter case you see there is no formatting but plain text.

Some context: the GetFeatureInfo response is rendered by MapStore using a (optional) template. GeoNode inflates the template inside the map config dynamically. It oprovides either a default template or one created according to the settings inside the attributes tab of the metadata page (see image below).

Apparrently the template is inflated only for one layer (I guess the one the map was created from) but not for the additional layers that have been added afterwards. We probably need to extend the adapter to pass the templates for these layers too.

![image](https://user-images.githubusercontent.com/571129/139074853-a059481e-c856-465d-b9bc-f078a005d55d.png)

**Comment by lsntdev** [comment] 2022-01-06 17:20
I found this too, I think it is a **bug**. The fix 8e8e9a1c05f876e256c2ed63b4e09f9f4b3d1ef4 in the adapter did not work as this is not called during add layer (catalog plugins). More precisely, any of the hook were called so the layer added was not converted, to see that you can enable debug and the two layer in the state are different.

**Notice**: The original layer (the map created from) doesn't not appear to have the same structure as the added one, it doesn't have anymore the key "getFeatureInfo", I guess it might come from geoserver not geonode. The list of the layer on the catalog is provided  [here](https://github.com/GeoNode/geonode/blob/master/geonode/catalogue/views.py#:~:text=%40csrf_exempt,content_type%3Dcsw.contenttype). 

This issue could be related to this https://github.com/GeoNode/geonode/issues/8345 , the query failed on layer intersection.

**Comment by giohappy** [comment] 2022-01-14 12:33
To recap:

 - we confirm that if a layer is added to a map through the "create map" and "add to map" actions, the GFI template is correctly added to the map config
 - when a layer is added from the CSW catalogue the template is not added, since the client has no way to retrieve it from CSW and the adapter doesn't inflati it on save.

@etj this is the expected behaviour, so I would close this issue again and, in case, open one to improve the behaviour.

**Closed** 2022-01-14 13:14 UTC
Labels: 3.3.x
